\documentclass[12pt,a4paper]{paper}
\usepackage[utf8]{inputenc}
\usepackage[english]{babel}
\usepackage{amsmath}
\usepackage{enumitem}
\usepackage{amsfonts}
\usepackage{multicol}
\usepackage{amssymb}
\usepackage{tikz}
\usepackage[left=1cm,right=1cm,top=1.5cm,bottom=2cm]{geometry}
\begin{document}
\title{GENE638 - Homework 1\\\small{Daniel Osorio - dcosorioh@tamu.edu\\Department of Veterinary Integrative Biosciences\\Texas A\&M University}}
\maketitle
\SweaveOpts{concordance=TRUE}
\begin{enumerate}
\item Given \[A = \left[\begin{array}{ccccc}-1 & 7 & 9 & -2 & 3\\ 3 & 13 & 10 & 2 & 6 \\ 11 & -9 & 0 & -3 & 2 \end{array}\right]B = \left[\begin{array}{ccc}1 & 0 & -1 \\ 1 & -1 & 0 \\ 1 & 1 & 1\end{array}\right]C = \left[\begin{array}{ccc}0 & -1 & -1 \\ -1 & 0 & -1 \\ -1 & -1 & 0\end{array}\right] \underline{y} = \left[\begin{array}{c}1\\2\\3\end{array}\right]\]
<<echo=FALSE>>=
A <- matrix(c(-1, 17, 9, -2, 3, 3, 13, 10, 2, 6, 11, -9, 0, -3, 2), nrow = 3, byrow = TRUE)
B <- matrix(c(1 , 0 , -1 , 1 , -1 , 0 , 1 , 1 , 1), nrow = 3, byrow = TRUE)
C <- matrix(c(0, -1, -1, -1, 0, -1, -1, -1, 0), nrow = 3, byrow = TRUE)
underlineY <- c(1, 2, 3)
@
\begin{enumerate}
\item Calculate:
\begin{enumerate}
\begin{multicols}{2}
\item $\sum_{i = 1}^{3}{b_{i1}}$
<<echo=TRUE>>=
sum(B[,1])
@
\item $\sum_{i = 1}^{3}{b_{i2}}$
<<echo=TRUE>>=
sum(B[,2])
@
\item $\sum_{i = 1}^{3}{b_{i3}}$
<<echo=TRUE>>=
sum(B[,3])
@
\item $\sum_{i = 1}^{j}{b_{ij}}$
<<echo=TRUE>>=
sum(B)
@
\end{multicols}
\end{enumerate}
\item Show that $1_{3}'B1_{3} = \sum_{i=1}^{3}{\sum_{j=1}^{3}{b_{ij}}}$
<<>>=
t(rep(1,3)) %*% B %*% rep(1,3)
sum(B)
all.equal(as.numeric(t(rep(1,3)) %*% B %*% rep(1,3)), sum(B))
@
\item Find $B + C$
<<>>=
B + C
@
\item Show that $(B + C)\underline{y} = B\underline{y} + C\underline{y}$
<<>>=
(B + C) %*% underlineY
B %*% underlineY + C %*% underlineY
all.equal((B + C) %*% underlineY, B %*% underlineY + C %*% underlineY)
@
\item Find $A'(B + C)\underline{y}$
<<>>=
t(A) %*% (B + C) %*% underlineY
@
\end{enumerate}
\item In this comunication network, messages can be sent only in the direction of the arrows:
\begin{center}
\tikzset{every picture/.style={line width=0.75pt}} %set default line width to 0.75pt        

\begin{tikzpicture}[x=0.75pt,y=0.75pt,yscale=-1,xscale=1]
%uncomment if require: \path (0,404); %set diagram left start at 0, and has height of 404
%Straight Lines
\draw    (140,126) -- (175.5,126) ;
\draw [shift={(177.5,126)}, rotate = 180] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines
\draw    (140,126) -- (176.32,175.39) ;
\draw [shift={(177.5,177)}, rotate = 233.67000000000002] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines
\draw    (198.5,126) -- (246.5,126) ;
\draw [shift={(248.5,126)}, rotate = 180] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines
\draw    (256.5,134) -- (256.97,167) ;
\draw [shift={(257,169)}, rotate = 269.18] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines
\draw    (198.5,174) -- (245.5,174) ;
\draw [shift={(247.5,174)}, rotate = 180] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines
\draw    (245.5,179) -- (198.5,179) ;
\draw [shift={(196.5,179)}, rotate = 360] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
%Straight Lines
\draw    (185.5,135) -- (185.97,168) ;
\draw [shift={(186,170)}, rotate = 269.18] [color={rgb, 255:red, 0; green, 0; blue, 0 }  ][line width=0.75]    (10.93,-3.29) .. controls (6.95,-1.4) and (3.31,-0.3) .. (0,0) .. controls (3.31,0.3) and (6.95,1.4) .. (10.93,3.29)   ;
% Text Node
\draw (128,126) node  [align=left] {K{\tiny 1}};
% Text Node
\draw (188,126) node  [align=left] {K{\tiny 2}};
% Text Node
\draw (188,176) node  [align=left] {K{\tiny 3}};
% Text Node
\draw (258,127) node  [align=left] {K{\tiny 4}};
% Text Node
\draw (259,177) node  [align=left] {K{\tiny 5}};
\end{tikzpicture}
\end{center}
Message routes can be represented by a matrix $W = w_{ij}$, where $w_{ij} = 0$ except $w_{ij} = 1$ if a message can be sent from $K_{i}$ to $K_{j}$.\[W = \left[\begin{array}{ccccc}
0 & 1 & 1 & 0 & 0 \\ 
0 & 0 & 1 & 1 & 0 \\ 
0 & 0 & 0 & 0 & 1 \\ 
0 & 0 & 0 & 0 & 1 \\ 
0 & 0 & 1 & 0 & 0 \\ 
\end{array}\right]\] In the $r^{th}$ power of this matrix $W^{r} = {w_{ij}(r)}, w_{ij}(r)$ is the number of ways of getting a message from $K_{i}$ to $K_{j}$ in $r$ steps.
\begin{enumerate}
<<echo=FALSE>>=
W <- matrix(c(0,1,1,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0), ncol = 5, byrow = TRUE)
@
\item Find $W^{2}$. Identify the paths that a message can go from $K_{2}$ to $K_{5}$ in 2 steps
<<>>=
W %*% W
@
The paths are: $K_{2} \rightarrow K_{4} \rightarrow K_{5}$, and $K_{2} \rightarrow K_{3} \rightarrow K_{5}$
\item Find $W^{3}$. Identify the paths that a message can go from $K_{2}$ to $K_{3}$ in 3 steps
<<>>=
W %*% W %*% W
@
The paths are $K_{2} \rightarrow K_{4} \rightarrow K_{5} \rightarrow K_{3}$ and $K_{2} \rightarrow K_{3} \rightarrow K_{5} \rightarrow K_{3}$
\end{enumerate}
\item For $A\underline{x} = \underline{b}$ where $A = \left[\begin{array}{ccc}2 & -2 & -1\\1 & 1 & -2 \\ 1 & 0 & -1\end{array}\right]$ and $\underline{b} = \left[\begin{array}{c}5 \\ 1\\ 4\end{array}\right]$
\begin{enumerate}
<<echo=FALSE>>=
A <- matrix(c(2,-2,-1,1,1,-2,1,0,-1), nrow = 3, byrow = TRUE)
b <- c(5, 1, 4)
@
\item Find the rank of $A$
<<>>=
as.numeric(Matrix::rankMatrix(A))
@
\item Show that $B = \left[\begin{array}{ccc}-1 & -2 & 5 \\ -1 & -1 & 3 \\ -1 & -2 & 4\end{array}\right] = A^{-1}$
<<echo=FALSE>>=
B <- matrix(c(-1 , -2 , 5 , -1 , -1 , 3 , -1 , -2 , 4),nrow = 3, byrow = TRUE)
@
<<>>=
solve(A)
all.equal(B, solve(A))
@
\item Solve for $\underline{x}$
<<>>=
solve(A) %*% b
@
\end{enumerate}
\end{enumerate}
\end{document}